title: Intro-Applied-Numerical-Groundwater-Modeling
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gw-inux.github.io/Course--Intro-Applied-Numerical-Groundwater-Modeling

aux_links:
  Template Repository: https://github.com/gw-inux/Course--Intro-Applied-Numerical-Groundwater-Modeling
